### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by Bensong0506** [li-plus/DSNet#15]
Hi,

May I ask why there are five .pt file for each datasets in the pre-trained model. I have tried the model on the default customer video and all five file provides quite different results. Which one should I choose? Thanks in advance.

**Comment by li-plus** [comment]
Because we train our model 5 times on each dataset config, and each time the dataset is randomly split into training & validation sets. The dataset is too small to train a stable model. Maybe you could train it on a larger dataset.
