### ISSUE TITLE
How can I know the original video name for the h5 file 

### ISSUE THREAD

**Issue by WujiangXu** [li-plus/DSNet#17]
hello, I want to extract the feature and train the network. But I don't know the original video name  in the eccv16_dataset_tvsum_google_pool5.h5 on the tvsum dataset.

**Comment by li-plus** [comment]
For SumMe dataset, video names are recorded in the h5 file. You could retrieve them by running the below script.

```python
import h5py

with h5py.File('./datasets/eccv16_dataset_summe_google_pool5.h5') as h5in:
    print(h5in['video_1']['video_name'][...])
```

For TVSum dataset, you could download the original data from the [official website](http://people.csail.mit.edu/yalesong/tvsum/). Video meta information is stored at `tvsum50_ver_1_1/ydata-tvsum50-v1_1/data/ydata-tvsum50-info.tsv`, where from top to bottom are video_1, video_2, ..., respectively. For example, the first 3 lines are listed as follows, corresponding to video_1, video_2, video_3.

```
category	video_id	title	url	length
VT	AwmHb44_ouw	#1306 How to change tires for off road vehicles [Davidsfarm]	https://www.youtube.com/watch?v=AwmHb44_ouw	5:54
VT	98MoyGZKHXc	How to use a tyre repair kit - Which? guide	https://www.youtube.com/watch?v=98MoyGZKHXc	3:07
VT	J0nA4VgnoCo	#0001: FLAT TIRE	https://www.youtube.com/watch?v=J0nA4VgnoCo	9:44
```

**Comment by WujiangXu** [comment]
> For SumMe dataset, video names are recorded in the h5 file. You could retrieve them by running the below script.
> 
> ```python
> import h5py
> 
> with h5py.File('./datasets/eccv16_dataset_summe_google_pool5.h5') as h5in:
>     print(h5in['video_1']['video_name'][...])
> ```
> 
> For TVSum dataset, you could download the original data from the [official website](http://people.csail.mit.edu/yalesong/tvsum/). Video meta information is stored at `tvsum50_ver_1_1/ydata-tvsum50-v1_1/data/ydata-tvsum50-info.tsv`, where from top to bottom are video_1, video_2, ..., respectively. For example, the first 3 lines are listed as follows, corresponding to video_1, video_2, video_3.
> 
> ```
> category	video_id	title	url	length
> VT	AwmHb44_ouw	#1306 How to change tires for off road vehicles [Davidsfarm]	https://www.youtube.com/watch?v=AwmHb44_ouw	5:54
> VT	98MoyGZKHXc	How to use a tyre repair kit - Which? guide	https://www.youtube.com/watch?v=98MoyGZKHXc	3:07
> VT	J0nA4VgnoCo	#0001: FLAT TIRE	https://www.youtube.com/watch?v=J0nA4VgnoCo	9:44
> ```

There are 50 videos in the youtube dataset, but there are 40 videos recording in the h5 file. Can you tell me whether some videos are not be used?
