### ISSUE TITLE
About the statistics of dataset in Table 1

### ISSUE THREAD

**Issue by leeynnnn** [li-plus/DSNet#18]
In Table 1 of the paper, I found that the TVSum, YouTube, and OVP datasets have the SAME duration(Min, Max, Avg). Are they correct? 

and how could i get the OVP and youtube dataset?

**Comment by li-plus** [comment]
They are not correct. Sorry for the mistake in our paper.

OVP & YouTube datasets can be found [here](https://sites.google.com/site/vsummsite/download).

**Comment by leeynnnn** [comment]
Sorry for bother you again.

When i download youtube video dataset, i found there are 50 files in _new_database.zip_, including 10 *.flv files and 40 *.avi files. Which 39 videos are used for training/evaluating in the experiment? Or are there some mistakes in my process?

Thank you very much!

**Comment by StevRamos** [comment]
@timemanager-001  They excluded cartoon videos so they are 50-11 = 39 videos without them
