### ISSUE TITLE
ABOUT SPLITS

### ISSUE THREAD

**Issue by StevRamos** [li-plus/DSNet#20]
Hi, I was looking for the correct splits of the datasets so in that way I could experiment correctly, but I found this split https://github.com/ok1zjf/VASNet/tree/master/splits and differs with the one you made. They used the same datasets so I was wondering if you know where is the correct one. Thanks!

**Comment by li-plus** [comment]
There is no "correct" split, because these datasets do not provide an official split file. Everybody creates his own one and runs experiments.
