### ISSUE TITLE
Incompatibility (CUDA and torch-sparse)

### ISSUE THREAD

**Issue by Luizerko** [li-plus/DSNet#22]
Hello guys.

I'm currently running some experiments on the DSNet, but every time I need to set up the network on a different environment I have problems with the `pip install -r requirements.txt`. It happens primarily because of `torch-spare` package. It's not compatible with several CUDA versions. Maybe it's a good idea to add to the README building `pytorch` and `torch-sparse` from source as recommendations.

Some useful links:
Building `pytorch` from source -> https://github.com/pytorch/pytorch
Premade wheels for `pip` installing `pytorch` -> https://download.pytorch.org/whl/torch/
Bulding `torch-sparse` from source -> https://github.com/rusty1s/pytorch_sparse
Premade wheels for `pip` installing `torch-sparse` -> https://pytorch-geometric.com/whl/

Thank you very much for your amazing network.

**Comment by Wazaki-Ou** [comment]
Hey @Luizerko . I'm trying to setup an environment to run DSNet too and I'm facing the same issue you are mentioning, so I'm wondering if you could please share some examples of compatible versions of CUDA, torch, torch-spare etc... I've been trying for a while but can't get it together. 
Thanks in advance !!
