### ISSUE TITLE
How to run the baseline model ？

### ISSUE THREAD

**Issue by huuuuyl** [li-plus/DSNet#4]
I want get the result ''For the baseline, we removed the interest proposal formulation and only applied a self-attention layer to predict the importance scores.'',How to run the baseline model ？Looking forward to your reply.

**Comment by li-plus** [comment]
To run the baseline, you will have to remove the anchor pre-processing & post-processing in both training and evaluation. It requires a fair amount of code change in this framework. A much easier way is to run [VASNet](https://github.com/ok1zjf/VASNet). They are exactly what you're looking for - using a self-attention layer to predict the importance scores. Our baseline model is also adapted from it by replacing its self-attention layer with ours.

**Comment by huuuuyl** [comment]
> To run the baseline, you will have to remove the anchor pre-processing & post-processing in both training and evaluation. It requires a fair amount of code change in this framework. A much easier way is to run [VASNet](https://github.com/ok1zjf/VASNet). They are exactly what you're looking for - using a self-attention layer to predict the importance scores. Our baseline model is also adapted from it by replacing its self-attention layer with ours.

thank you for your kind advice.

**Comment by li-plus** [comment]
My pleasure. Closing this issue. You may re-open it if necessary.
