### ISSUE TITLE
How to generate summaries on new videos?

### ISSUE THREAD

**Issue by timemanager-001** [li-plus/DSNet#5]
The code could generate video summaries on TVSum and SumMe dataset. If there are some new videos, how could we generate summaries on them? 

I found the data file contains "change_points", "n_frame_per_seg", do we have to get these annotations before we can generate summaries for new videos?

**Comment by tingxueronghua** [comment]
The information about shots is generated using KTS, I think the file make_shots.py under /src is enough to generate these parameters.

**Comment by Akash-Kunwar** [comment]
could you please share some steps to summarize the custom video

**Comment by iamyugachang** [comment]
Hi there @Akash-Kunwar,

I have generated summary videos on custom videos following this discussion: [https://github.com/KaiyangZhou/vsumm-reinforce/issues/1](https://github.com/KaiyangZhou/vsumm-reinforce/issues/1)
I summarized the process of generating summary video in the following steps:

1. Feature extraction:
Generate features extracted by GoogLeNet from the original videos, and create your custom h5 datasets.
Feature extraction:
```
features = []
for frame in video_frames:
    # frame is a numpy array of shape (channel, height, width)
    # do some preprocessing such as normalization
    frame = preprocess(frame)
    # apply the feature extractor to this frame
    feature = feature_extractor(frame)
    # save the feature
    features.append(feature)
features = concatenate(features) # now shape is (n_steps, feature_dimension)
```
Generate h5 dataset:
```
import h5py
h5_file_name = 'blah blah blah'
f = h5py.File(h5_file_name, 'w')

# video_names is a list of strings containing the 
# name of a video, e.g. 'video_1', 'video_2'
for name in video_names:
    f.create_dataset(name + '/features', data=data_of_name)
    f.create_dataset(name + '/gtscore', data=data_of_name)
    f.create_dataset(name + '/user_summary', data=data_of_name)
    f.create_dataset(name + '/change_points', data=data_of_name)
    f.create_dataset(name + '/n_frame_per_seg', data=data_of_name)
    f.create_dataset(name + '/n_frames', data=data_of_name)
    f.create_dataset(name + '/picks', data=data_of_name)
    f.create_dataset(name + '/n_steps', data=data_of_name)
    f.create_dataset(name + '/gtsummary', data=data_of_name)
    f.create_dataset(name + '/video_name', data=data_of_name)

f.close()
```
2. Apply KTS Algorithm:
There are `change_points` & `n_frame_per_seg` which stand for scene change segment in the TVSUM & SUMME datasets, so you have to create segment on your custom video as well. DSNet utilize KTS to create segment in `make_shots.py`. (There's no need of `gtscore` and `gtsummary`, please ignore them directly.)

3. Generate summary video:
After creating the complete h5 dataset in previous steps, you can execute `evaluate.py` and return a frame-level selection array of the original video. (ex: if `n_frame` of the original_video is 5, then the selection array could be [0,0,1,1,0])
```
pred_summ = prediction()
cap = cv2.VideoCapture(....)
out = cv2.VideoWriter(....)
for frame in range(n_frames):
    ret, frame = cap.read()
    if pred_summ[frame]:
        out.write(frame)
cap.release()
out.release()
```

**Comment by li-plus** [comment]
Hi all, I have provided scripts for training & validation & inference on custom videos in the latest commit. Please follow the instructions in `README.md` and check out the sample videos in `custom_data` folder.

Sorry to keep you waiting but I was super busy the last 2 months. Thank you all for your patience. Appreciate @tingxueronghua & @iamyugachang for your help.

Closing this issue. Reopen it if necessary.

**Comment by mohammedshady** [comment]
> I have provided scripts for training & validation & inference on custom videos in the latest commit

hey man im sorry to bother but ive tried to regenerate the dataset by downloading tvsum original videos and labels and running the make_dataset and it seems to generate different features, change points, gt_score ( even after i used the original dataset h5 user summary it still gave a different gt_score 
i tried running the model with the new features, changepoints, etc.. but i got really bad fscore compared to the original dataset file

**Comment by bigteeth43** [comment]
> Hi all, I have provided scripts for training & validation & inference on custom videos in the latest commit. Please follow the instructions in `README.md` and check out the sample videos in `custom_data` folder.
> 
> Sorry to keep you waiting but I was super busy the last 2 months. Thank you all for your patience. Appreciate @tingxueronghua & @iamyugachang for your help.
> 
> Closing this issue. Reopen it if necessary.

how can i get the json project,the dataset has videos and labels,but i can not get the labels,so i can not go into the make.dataset

**Comment by mohammedshady** [comment]
> but i can not get the labels

if you downloaded the original (tvsum) dataset `http://people.csail.mit.edu/yalesong/tvsum` you will find folder with the videos and a `ydata-tvsum50-anno.tsv` file with the annotations for each video this file has the video title and the importance scores of each frame for that video.
if you want to recreate the tvsum dataset you will have to pull out these labels and save them in json file for each video.

**Comment by bigteeth43** [comment]
> > 但我不能得到标签
> 
> 如果您下载了原始 (tvsum) 数据集`http://people.csail.mit.edu/yalesong/tvsum`你会发现文件夹中的视频和一个`ydata-tvsum50-anno.tsv`带有每个视频的注释的文件该文件具有该视频的视频标题和每个帧的重要性分数。 如果要重新创建tvsum数据集，则必须拉出这些标签并将其保存在每个视频的json文件中。



> > but i can not get the labels
> 
> if you downloaded the original (tvsum) dataset `http://people.csail.mit.edu/yalesong/tvsum` you will find folder with the videos and a `ydata-tvsum50-anno.tsv` file with the annotations for each video this file has the video title and the importance scores of each frame for that video. if you want to recreate the tvsum dataset you will have to pull out these labels and save them in json file for each video.

thank you for your answer ,but i want to make my own dataset, so what is rule of the importance scores of each frame for that video of the tvsum?

**Comment by bigteeth43** [comment]
> > > 但我不能得到标签
> > 
> > 
> > 如果您下载了原始 (tvsum) 数据集`http://people.csail.mit.edu/yalesong/tvsum`你会发现文件夹中的视频和一个`ydata-tvsum50-anno.tsv`带有每个视频的注释的文件该文件具有该视频的视频标题和每个帧的重要性分数。 如果要重新创建tvsum数据集，则必须拉出这些标签并将其保存在每个视频的json文件中。
> 
> > > 但我不能得到标签
> > 
> > 
> > 如果您下载了原始 (tvsum) 数据集`http://people.csail.mit.edu/yalesong/tvsum`你会发现文件夹中的视频和一个`ydata-tvsum50-anno.tsv`带有每个视频的注释的文件该文件具有该视频的视频标题和每个帧的重要性分数。如果要重新创建tvsum数据集，则必须拉出这些标签并将其保存在每个视频的json文件中。
> 
> 感谢您的回答，但我想制作自己的数据集，那么tvsum的视频的每个帧的重要性分数的规则是什么？


> > > 但我不能得到标签
> > 
> > 
> > 如果您下载了原始 (tvsum) 数据集`http://people.csail.mit.edu/yalesong/tvsum`你会发现文件夹中的视频和一个`ydata-tvsum50-anno.tsv`带有每个视频的注释的文件该文件具有该视频的视频标题和每个帧的重要性分数。 如果要重新创建tvsum数据集，则必须拉出这些标签并将其保存在每个视频的json文件中。
> 
> > > but i can not get the labels
> > 
> > 
> > if you downloaded the original (tvsum) dataset `http://people.csail.mit.edu/yalesong/tvsum` you will find folder with the videos and a `ydata-tvsum50-anno.tsv` file with the annotations for each video this file has the video title and the importance scores of each frame for that video. if you want to recreate the tvsum dataset you will have to pull out these labels and save them in json file for each video.
> 
> thank you for your answer ,but i want to make my own dataset, so what is rule of the importance scores of each frame for that video of the tvsum?

at first,i think i just need to point the each frame of the video,but the number is different from the number in ydata-tvsum50-anno.tsv

**Comment by mohammedshady** [comment]
> what is rule of the importance scores of each frame for that video of the tvsum

so the importance scores are basically a rating of each frame in the video.
such process can take a long time so you can downsample the video to 2 frames per second instead of 30 and basically label each frame in a json array with comma separated values like [2,3,4,4,4,2....,2,1,1,1] you can either use numbers from (1 to 5 ) and normalize them or (0.0 to 0.99) after you are done with labeling now you have what they call the gtscore you can derive the user_summary from the gt_score by calling the `get_key_shot_summ()` in the `vsum_helper` and pass the gtscore as 
the first parameter. To get other parameters for this function you need to extract the change points and other values by calling the `videoPreprocessor.run()` in `video_helper` which will return everything you need.
im pretty sure the make_shots.py have something to do with that but i haven't used it before.

**Comment by mohammedshady** [comment]
> at first,i think i just need to point the each frame of the video,but the number is different from the number in ydata-tvsum50-anno.tsv

im not sure what do you mean but some videos have less or more frames (1 or 2) like when you read a video it is `10456 frames `but in the annotations it is `10455 frames` so you can just pad the annotation by the number of video frames and if it is more than you can cut the annotations till the number of frames (that only happened to me in 3 videos btw and the difference was 1 frame)
-just make sure the annotations belong to that video and not any other video.

**Comment by bigteeth43** [comment]
> > 起初，我想我只需要指出视频的每一帧，但数字与ydata-tvsum50-anno.tsv中的数字不同
> 
> 我不知道你是什么意思，但有些视频有更少或更多的帧 (1或2) 像当你读一个视频`10456 frames `但在注释中它是`10455 frames`所以你可以通过视频帧数来填充注释，如果它超过了你可以剪切注释直到帧数 (这只发生在我身上的3个视频btw和差异为1帧) -只要确保注释属于该视频，而不是任何其他视频。

thank you,the mistake is done,the label consist of 20 groups.but i find the label score given by wirter  is 0 or 1 in custom_data ,but the tvsum is 0-5,so when training,what score is the writer using, if use 0or 1,and how can i get the tvsum's 01 score from writer  ?
