### ISSUE TITLE
While running the infer.py file for the custom video summarization I am getting an error 

### ISSUE THREAD

**Issue by Akash-Kunwar** [li-plus/DSNet#9]
Loading DSNet model ...
Preprocessing source video ...

#ERROR
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument

Predicting summary ...
Writing summary video ...

**Comment by li-plus** [comment]
It seems to be a CUDA error. I google this error and find this issue https://github.com/pytorch/pytorch/issues/15797. Does it help you?

**Comment by Akash-Kunwar** [comment]
Yes, I saw that issue but for me running the infer.py script again helped to resolve the error 
Thanks for helping
